server:
  port: 9091


spring:
  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:9095

  datasource:
    url: jdbc:mysql://localhost:3306/micro_users
    username: krsna
    password: Krsna@108
    driver-class-name: com.mysql.cj.jdbc.Driver

Logger:
  level:
    com.Krsna.UserService.external_services.HotelService: DEBUG
    com.Krsna.UserService.external_services.RatingService: DEBUG
